all:
	./jemdoc.py  -o ../ index.jemdoc
	./jemdoc.py  -o ../ member.jemdoc
	./jemdoc.py  -o ../ committee.jemdoc
	./jemdoc.py  -o ../ subcom.jemdoc
	./jemdoc.py  -o ../ activity.jemdoc
	./jemdoc.py  -o ../ letter.jemdoc
	#cp -rf eqs  ../
	./jemdoc.py  -o ../ TBD-CPS.jemdoc

