all:
	./jemdoc.py  -o ../ index.jemdoc
	./jemdoc.py  -o ../ scope.jemdoc
	./jemdoc.py  -o ../ committee.jemdoc
	./jemdoc.py  -o ../ member.jemdoc
	./jemdoc.py  -o ../ activity.jemdoc
	./jemdoc.py  -o ../ award.jemdoc
	#cp -rf eqs  ../

