all:
	./jemdoc.py  -o ../ index.jemdoc
	./jemdoc.py  -o ../ organization.jemdoc
	./jemdoc.py  -o ../ executive.jemdoc
	./jemdoc.py  -o ../ member.jemdoc
	./jemdoc.py  -o ../ activity.jemdoc
	./jemdoc.py  -o ../ news.jemdoc
	#cp -rf eqs  ../

